[phases.setup]
nixPkgs = ["...", "postgresql"]

[phases.build]
command = """
  cargo build --release &&
  mkdir -p /app/bin &&
  cp target/release/rustyspaces /app/bin/
"""

[phases.start]
command = "/app/bin/rustyspaces"