[phases.setup]
nixPkgs = ["...", "postgresql"]

[build]
command = """
  cargo build --release &&
  mkdir -p /app/bin &&
  cp target/release/rustyspaces /app/bin/
"""

[start]
command = "/app/bin/rustyspaces"